#ifndef DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__CADDR_T_H
#define DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__CADDR_T_H

typedef char *          bsd_caddr_t;

#endif // DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__CADDR_T_H