#ifndef DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT32_T_H
#define DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT32_T_H

typedef int                     bsd_int32_t;

#endif // DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT32_T_H