#ifndef DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT16_T_H
#define DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT16_T_H

typedef short                   bsd_int16_t;

#endif // DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT16_T_H