#ifndef DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT64_T_H
#define DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT64_T_H

typedef long long               bsd_int64_t;

#endif // DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT64_T_H