#ifndef DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT8_T_H
#define DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT8_T_H

typedef signed char           bsd_int8_t;

#endif // DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__INT8_T_H