#ifndef DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__U_INT16_T_H
#define DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__U_INT16_T_H

typedef unsigned short                  bsd_u_int16_t;

#endif // DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__U_INT16_T_H