#ifndef DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__U_INT32_T_H
#define DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__U_INT32_T_H

typedef unsigned int            bsd_u_int32_t;

#endif // DARLING_EMULATION_CONVERSION_BSD_SYS__TYPES__U_INT32_T_H