#ifndef DARLING_EMULATION_CONVERSION_BSD_SYS_CONF_H
#define DARLING_EMULATION_CONVERSION_BSD_SYS_CONF_H

#define	BSD_D_TAPE  1
#define	BSD_D_DISK  2
#define	BSD_D_TTY   3

#endif // DARLING_EMULATION_CONVERSION_BSD_SYS_CONF_H
