#ifndef DARLING_EMULATION_CONVERSION_BSD_SYS_ERRNO_H
#define DARLING_EMULATION_CONVERSION_BSD_SYS_ERRNO_H

#define BSD_EPERM 1 
#define BSD_ENOENT 2 
#define BSD_ESRCH 3 
#define BSD_EINTR 4 
#define BSD_EIO 5 
#define BSD_ENXIO 6 
#define BSD_E2BIG 7 
#define BSD_ENOEXEC 8 
#define BSD_EBADF 9 
#define BSD_ECHILD 10
#define BSD_EDEADLK 11
#define BSD_ENOMEM 12        
#define BSD_EACCES 13        
#define BSD_EFAULT 14        
#define BSD_ENOTBLK 15
#define BSD_EBUSY 16
#define BSD_EEXIST 17
#define BSD_EXDEV 18
#define BSD_ENODEV 19
#define BSD_ENOTDIR 20
#define BSD_EISDIR 21
#define BSD_EINVAL 22
#define BSD_ENFILE 23
#define BSD_EMFILE 24
#define BSD_ENOTTY 25
#define BSD_ETXTBSY 26
#define BSD_EFBIG 27
#define BSD_ENOSPC 28
#define BSD_ESPIPE 29
#define BSD_EROFS 30
#define BSD_EMLINK 31
#define BSD_EPIPE 32

#define BSD_EDOM 33
#define BSD_ERANGE 34

#define BSD_EAGAIN 35
#define BSD_EWOULDBLOCK BSD_EAGAIN
#define BSD_EINPROGRESS 36
#define BSD_EALREADY 37

#define BSD_ENOTSOCK 38
#define BSD_EDESTADDRREQ 39
#define BSD_EMSGSIZE 40
#define BSD_EPROTOTYPE 41
#define BSD_ENOPROTOOPT 42
#define BSD_EPROTONOSUPPORT 43
#define BSD_ESOCKTNOSUPPORT 44
#define BSD_ENOTSUP 45

#define BSD_EPFNOSUPPORT 46
#define BSD_EAFNOSUPPORT 47
#define BSD_EADDRINUSE 48
#define BSD_EADDRNOTAVAIL 49

#define BSD_ENETDOWN 50
#define BSD_ENETUNREACH 51
#define BSD_ENETRESET 52
#define BSD_ECONNABORTED 53
#define BSD_ECONNRESET 54
#define BSD_ENOBUFS 55
#define BSD_EISCONN 56
#define BSD_ENOTCONN 57
#define BSD_ESHUTDOWN 58
#define BSD_ETOOMANYREFS 59
#define BSD_ETIMEDOUT 60
#define BSD_ECONNREFUSED 61

#define BSD_ELOOP 62
#define BSD_ENAMETOOLONG 63

#define BSD_EHOSTDOWN 64
#define BSD_EHOSTUNREACH 65
#define BSD_ENOTEMPTY 66

#define BSD_EPROCLIM 67
#define BSD_EUSERS 68
#define BSD_EDQUOT 69

#define BSD_ESTALE 70
#define BSD_EREMOTE 71
#define BSD_EBADRPC 72
#define BSD_ERPCMISMATCH 73
#define BSD_EPROGUNAVAIL 74
#define BSD_EPROGMISMATCH 75
#define BSD_EPROCUNAVAIL 76

#define BSD_ENOLCK 77
#define BSD_ENOSYS 78

#define BSD_EFTYPE 79
#define BSD_EAUTH 80
#define BSD_ENEEDAUTH 81

#define BSD_EPWROFF 82
#define BSD_EDEVERR 83

#define BSD_EOVERFLOW 84

#define BSD_EBADEXEC 85
#define BSD_EBADARCH 86
#define BSD_ESHLIBVERS 87
#define BSD_EBADMACHO 88

#define BSD_ECANCELED 89

#define BSD_EIDRM 90
#define BSD_ENOMSG 91
#define BSD_EILSEQ 92
#define BSD_ENOATTR 93

#define BSD_EBADMSG 94 
#define BSD_EMULTIHOP 95 
#define BSD_ENODATA 96 
#define BSD_ENOLINK 97 
#define BSD_ENOSR 98 
#define BSD_ENOSTR 99 
#define BSD_EPROTO 100
#define BSD_ETIME 101

#define BSD_EOPNOTSUPP 102

#define BSD_ENOPOLICY 103

#define BSD_ENOTRECOVERABLE 104
#define BSD_EOWNERDEAD 105

#define BSD_EQFULL 106
#define BSD_ELAST 106

#endif // DARLING_EMULATION_CONVERSION_BSD_SYS_ERRNO_H
