#ifndef DARLING_EMULATION_CONVERSION_BSD_SYS_MMAN_H
#define DARLING_EMULATION_CONVERSION_BSD_SYS_MMAN_H

#define BSD_PROT_NONE  0x00
#define BSD_PROT_READ  0x01
#define BSD_PROT_WRITE 0x02
#define BSD_PROT_EXEC  0x04

#define BSD_MAP_SHARED  0x0001
#define BSD_MAP_PRIVATE 0x0002

#define BSD_MAP_FIXED 0x0010

#define BSD_MAP_ANON      0x1000

#endif // DARLING_EMULATION_CONVERSION_BSD_SYS_MMAN_H