#ifndef DARLING_EMULATION_CONVERSION_BSD_SYS_SYSLIMITS_H
#define DARLING_EMULATION_CONVERSION_BSD_SYS_SYSLIMITS_H

#define BSD_NGROUPS_MAX     16

#define BSD_PATH_MAX        1024

#endif // DARLING_EMULATION_CONVERSION_BSD_SYS_SYSLIMITS_H