#ifndef DARLING_EMULATION_CONVERSION_LINUX_BITS_POSIX_OPT_H
#define DARLING_EMULATION_CONVERSION_LINUX_BITS_POSIX_OPT_H

#define LINUX__POSIX_VDISABLE ((unsigned char)'\0')

#endif // DARLING_EMULATION_CONVERSION_LINUX_BITS_POSIX_OPT_H