#ifndef DARLING_EMULATION_CONVERSION_LINUX_ASM_TYPES_H
#define DARLING_EMULATION_CONVERSION_LINUX_ASM_TYPES_H

#include <emulation/conversion/variables/linux/asm-generic/types.h>

#endif // DARLING_EMULATION_CONVERSION_LINUX_ASM_TYPES_H
