#include <emulation/conversion/methods/errno.h>

#include <emulation/conversion/variables/linux/asm-generic/errno.h>

#include <stddef.h>

static const int linux_to_darwin[512] = {
	[LINUX_EPERM] = BSD_EPERM,
	[LINUX_ENOENT] = BSD_ENOENT,
	[LINUX_ESRCH] = BSD_ESRCH,
	[LINUX_EINTR] = BSD_EINTR,
	[LINUX_EIO] = BSD_EIO,
	[LINUX_ENXIO] = BSD_ENXIO,
	[LINUX_ENOEXEC] = BSD_ENOEXEC,
	[LINUX_EBADF] = BSD_EBADF,
	[LINUX_ECHILD] = BSD_ECHILD,
	[LINUX_EDEADLK] = BSD_EDEADLK,
	[LINUX_ENOMEM] = BSD_ENOMEM,
	[LINUX_EACCES] = BSD_EACCES,
	[LINUX_EFAULT] = BSD_EFAULT,
	[LINUX_ENOTBLK] = BSD_ENOTBLK,
	[LINUX_EBUSY] = BSD_EBUSY,
	[LINUX_EEXIST] = BSD_EEXIST,
	[LINUX_EXDEV] = BSD_EXDEV,
	[LINUX_ENODEV] = BSD_ENODEV,
	[LINUX_ENOTDIR] = BSD_ENOTDIR,
	[LINUX_EISDIR] = BSD_EISDIR,
	[LINUX_EINVAL] = BSD_EINVAL,
	[LINUX_ENFILE] = BSD_ENFILE,
	[LINUX_EMFILE] = BSD_EMFILE,
	[LINUX_ENOTTY] = BSD_ENOTTY,
	[LINUX_ETXTBSY] = BSD_ETXTBSY,
	[LINUX_EFBIG] = BSD_EFBIG,
	[LINUX_ENOSPC] = BSD_ENOSPC,
	[LINUX_ESPIPE] = BSD_ESPIPE,
	[LINUX_EROFS] = BSD_EROFS,
	[LINUX_EMLINK] = BSD_EMLINK,
	[LINUX_EPIPE] = BSD_EPIPE,
	[LINUX_EDOM] = BSD_EDOM,
	[LINUX_ERANGE] = BSD_ERANGE,
	[LINUX_EAGAIN] = BSD_EAGAIN,
	[LINUX_EINPROGRESS] = BSD_EINPROGRESS,
	[LINUX_EALREADY] = BSD_EALREADY,
	[LINUX_ENOTSOCK] = BSD_ENOTSOCK,
	[LINUX_EDESTADDRREQ] = BSD_EDESTADDRREQ,
	[LINUX_EMSGSIZE] = BSD_EMSGSIZE,
	[LINUX_EPROTOTYPE] = BSD_EPROTOTYPE,
	[LINUX_ENOPROTOOPT] = BSD_ENOPROTOOPT,
	[LINUX_EPROTONOSUPPORT] = BSD_EPROTONOSUPPORT,
	[LINUX_ESOCKTNOSUPPORT] = BSD_ESOCKTNOSUPPORT,
	[LINUX_EPFNOSUPPORT] = BSD_EPFNOSUPPORT,
	[LINUX_EAFNOSUPPORT] = BSD_EAFNOSUPPORT,
	[LINUX_EADDRINUSE] = BSD_EADDRINUSE,
	[LINUX_EADDRNOTAVAIL] = BSD_EADDRNOTAVAIL,
	[LINUX_ENETDOWN] = BSD_ENETDOWN,
	[LINUX_ENETUNREACH] = BSD_ENETUNREACH,
	[LINUX_ENETRESET] = BSD_ENETRESET,
	[LINUX_ECONNABORTED] = BSD_ECONNABORTED,
	[LINUX_ECONNRESET] = BSD_ECONNRESET,
	[LINUX_ENOBUFS] = BSD_ENOBUFS,
	[LINUX_EISCONN] = BSD_EISCONN,
	[LINUX_ENOTCONN] = BSD_ENOTCONN,
	[LINUX_ESHUTDOWN] = BSD_ESHUTDOWN,
	[LINUX_ETOOMANYREFS] = BSD_ETOOMANYREFS,
	[LINUX_ETIMEDOUT] = BSD_ETIMEDOUT,
	[LINUX_ECONNREFUSED] = BSD_ECONNREFUSED,
	[LINUX_ELOOP] = BSD_ELOOP,
	[LINUX_ENAMETOOLONG] = BSD_ENAMETOOLONG,
	[LINUX_EHOSTDOWN] = BSD_EHOSTDOWN,
	[LINUX_EHOSTUNREACH] = BSD_EHOSTUNREACH,
	[LINUX_ENOTEMPTY] = BSD_ENOTEMPTY,
	[LINUX_EUSERS] = BSD_EUSERS,
	[LINUX_EDQUOT] = BSD_EDQUOT,
	[LINUX_ESTALE] = BSD_ESTALE,
	[LINUX_EREMOTE] = BSD_EREMOTE,
	[LINUX_ENOLCK] = BSD_ENOLCK,
	[LINUX_ENOSYS] = BSD_ENOSYS,
	[LINUX_EOVERFLOW] = BSD_EOVERFLOW,
	[LINUX_ECANCELED] = BSD_ECANCELED,
	[LINUX_EIDRM] = BSD_EIDRM,
	[LINUX_ENOMSG] = BSD_ENOMSG,
	[LINUX_EILSEQ] = BSD_EILSEQ,
	[LINUX_EBADMSG] = BSD_EBADMSG,
	[LINUX_EMULTIHOP] = BSD_EMULTIHOP,
	[LINUX_ENODATA] = BSD_ENODATA,
	[LINUX_ENOLINK] = BSD_ENOLINK,
	[LINUX_ENOSR] = BSD_ENOSR,
	[LINUX_ENOSTR] = BSD_ENOSTR,
	[LINUX_EPROTO] = BSD_EPROTO,
	[LINUX_ETIME] = BSD_ETIME,

	// On both Linux & macOS, EOPNOTSUPP & ENOTSUP are the same
	[LINUX_EOPNOTSUPP] = BSD_EOPNOTSUPP,
};
const size_t length_of_translation_array = sizeof(linux_to_darwin)/sizeof(const int);

int errno_linux_to_bsd(int err)
{
	int v = err;
	if (v < 0)
		v = -v;

	if ((v < length_of_translation_array) && (linux_to_darwin[v]))
	{
		v = linux_to_darwin[v];
		return (err < 0) ? -v : v;
	}

	return err;
}

