#ifndef DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_ERRNO_BASE_H
#define DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_ERRNO_BASE_H

#define	LINUX_EPERM		 1
#define	LINUX_ENOENT	 2
#define	LINUX_ESRCH		 3
#define	LINUX_EINTR		 4
#define	LINUX_EIO		 5	
#define	LINUX_ENXIO		 6
#define	LINUX_E2BIG		 7
#define	LINUX_ENOEXEC	 8
#define	LINUX_EBADF		 9
#define	LINUX_ECHILD	10
#define	LINUX_EAGAIN	11
#define	LINUX_ENOMEM	12
#define	LINUX_EACCES	13
#define	LINUX_EFAULT	14
#define	LINUX_ENOTBLK	15
#define	LINUX_EBUSY		16
#define	LINUX_EEXIST	17
#define	LINUX_EXDEV		18
#define	LINUX_ENODEV	19
#define	LINUX_ENOTDIR	20
#define	LINUX_EISDIR	21
#define	LINUX_EINVAL	22
#define	LINUX_ENFILE	23
#define	LINUX_EMFILE	24
#define	LINUX_ENOTTY	25
#define	LINUX_ETXTBSY	26
#define	LINUX_EFBIG		27
#define	LINUX_ENOSPC	28
#define	LINUX_ESPIPE	29
#define	LINUX_EROFS		30
#define	LINUX_EMLINK	31
#define	LINUX_EPIPE		32
#define	LINUX_EDOM		33
#define	LINUX_ERANGE	34

#endif // DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_ERRNO_BASE_H