#ifndef DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_MMAN_COMMON_H
#define DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_MMAN_COMMON_H

#define LINUX_PROT_READ 0x1
#define LINUX_PROT_WRITE 0x2
#define LINUX_PROT_EXEC 0x4
#define LINUX_PROT_SEM 0x8
// 0x10
// 0x20
#define LINUX_PROT_NONE 0x0
#define LINUX_PROT_GROWSDOWN 0x01000000
#define LINUX_PROT_GROWSUP 0x02000000

#define LINUX_MAP_TYPE 0x0f
#define LINUX_MAP_FIXED 0x10
#define LINUX_MAP_ANONYMOUS 0x20

#define LINUX_MS_ASYNC 1
#define LINUX_MS_INVALIDATE 2
#define LINUX_MS_SYNC 4

#define LINUX_MADV_NORMAL 0
#define LINUX_MADV_RANDOM 1
#define LINUX_MADV_SEQUENTIAL 2
#define LINUX_MADV_WILLNEED 3
#define LINUX_MADV_DONTNEED 4

#define LINUX_MADV_REMOVE 9
#define LINUX_MADV_DONTFORK 10
#define LINUX_MADV_DOFORK 11
#define LINUX_MADV_HWPOISON 100
#define LINUX_MADV_SOFT_OFFLINE 101

#define LINUX_MADV_MERGEABLE 12
#define LINUX_MADV_UNMERGEABLE 13

#define LINUX_MADV_HUGEPAGE 14
#define LINUX_MADV_NOHUGEPAGE 15

#define LINUX_MADV_DONTDUMP 16
#define LINUX_MADV_DODUMP 17

#define LINUX_MAP_FILE 0

#endif // DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_MMAN_COMMON_H