#ifndef DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_MMAN_H
#define DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_MMAN_H

#include <emulation/conversion/variables/linux/asm-generic/mman-common.h>

#define LINUX_MAP_GROWSDOWN 0x0100
#define LINUX_MAP_DENYWRITE 0x0800
#define LINUX_MAP_EXECUTABLE 0x1000
#define LINUX_MAP_LOCKED 0x2000
#define LINUX_MAP_NORESERVE 0x4000

#define LINUX_MCL_CURRENT 1
#define LINUX_MCL_FUTURE 2

#endif // DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_MMAN_H