#ifndef DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_SOCKIOS_H
#define DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_SOCKIOS_H

#define LINUX_FIOSETOWN         0x8901
#define LINUX_SIOCSPGRP         0x8902
#define LINUX_FIOGETOWN         0x8903
#define LINUX_SIOCGPGRP         0x8904
#define LINUX_SIOCATMARK        0x8905
#define LINUX_SIOCGSTAMP_OLD    0x8906
#define LINUX_SIOCGSTAMPNS_OLD  0x8907

#endif //DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_SOCKIOS_H
