#ifndef DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_TYPES_H
#define DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_TYPES_H

#include <emulation/conversion/variables/linux/asm-generic/int-ll64.h>

#endif // DARLING_EMULATION_CONVERSION_LINUX_ASM_GENERIC_TYPES_H
