#ifndef DARLING_CONVERSION_MMAN_MSYNC
#define DARLING_CONVERSION_MMAN_MSYNC

#define LINUX_MS_ASYNC	1
#define LINUX_MS_INVALIDATE	2
#define LINUX_MS_SYNC	4

#define BSD_MS_ASYNC	1
#define BSD_MS_INVALIDATE	2
#define BSD_MS_SYNC		0x10

#endif // DARLING_CONVERSION_MMAN_MSYNC
