#ifndef DARLING_EMULATION_CONVERSION_BSD_NETINET_TCP_H
#define DARLING_EMULATION_CONVERSION_BSD_NETINET_TCP_H

#define BSD_TCP_NODELAY             0x01
#define BSD_TCP_MAXSEG              0x02
#define BSD_TCP_NOPUSH              0x04
#define BSD_TCP_NOOPT               0x08
#define BSD_TCP_KEEPALIVE           0x10
#define BSD_TCP_CONNECTIONTIMEOUT   0x20
#define BSD_PERSIST_TIMEOUT         0x40
#define BSD_TCP_RXT_CONNDROPTIME    0x80
#define BSD_TCP_RXT_FINDROP         0x100
#define BSD_TCP_KEEPINTVL           0x101
#define BSD_TCP_KEEPCNT             0x102

#endif // DARLING_EMULATION_CONVERSION_BSD_NETINET_TCP_H