#ifndef DARLING_BSD_EMULATION_DISABLE_THREADSIGNAL_H
#define DARLING_BSD_EMULATION_DISABLE_THREADSIGNAL_H

long sys_disable_threadsignal(int disable);

#endif // DARLING_BSD_EMULATION_DISABLE_THREADSIGNAL_H

