#ifndef DARLING_EMULATION_CONVERSION_LINUX_LINUX_FCNTL_H
#define DARLING_EMULATION_CONVERSION_LINUX_LINUX_FCNTL_H

#include <emulation/conversion/variables/linux/asm/fcntl.h>

#define LINUX_F_DUPFD_CLOEXEC	(LINUX_F_LINUX_SPECIFIC_BASE + 6)

#define LINUX_AT_FDCWD	-100

#define LINUX_AT_SYMLINK_NOFOLLOW   0x100

#define LINUX_AT_SYMLINK_FOLLOW	    0x400
#define LINUX_AT_NO_AUTOMOUNT       0x800
#define LINUX_AT_EMPTY_PATH         0x1000

#define LINUX_AT_REMOVEDIR			0x200

#endif // DARLING_EMULATION_CONVERSION_LINUX_LINUX_FCNTL_H