#ifndef DARLING_EMULATION_CONVERSION_LINUX_LINUX_IN6_H
#define DARLING_EMULATION_CONVERSION_LINUX_LINUX_IN6_H

#include <emulation/conversion/variables/linux/linux/libc-compat.h>

#if LINUX___UAPI_DEF_IPV6_OPTIONS
#define LINUX_IPV6_ADDRFORM         1
#define LINUX_IPV6_2292PKTINFO      2
#define LINUX_IPV6_2292HOPOPTS      3
#define LINUX_IPV6_2292DSTOPTS      4
#define LINUX_IPV6_2292RTHDR        5
#define LINUX_IPV6_2292PKTOPTIONS   6
#define LINUX_IPV6_CHECKSUM         7
#define LINUX_IPV6_2292HOPLIMIT     8
#define LINUX_IPV6_NEXTHOP          9
#define LINUX_IPV6_AUTHHDR          10
#define LINUX_IPV6_FLOWINFO         11

#define LINUX_IPV6_UNICAST_HOPS     16
#define LINUX_IPV6_MULTICAST_IF     17
#define LINUX_IPV6_MULTICAST_HOPS   18
#define LINUX_IPV6_MULTICAST_LOOP   19
#define LINUX_IPV6_ADD_MEMBERSHIP   20 // LINUX_IPV6_JOIN_GROUP
#define LINUX_IPV6_DROP_MEMBERSHIP  21 // LINUX_IPV6_LEAVE_GROUP
#define LINUX_IPV6_ROUTER_ALERT     22
#define LINUX_IPV6_MTU_DISCOVER     23
#define LINUX_IPV6_MTU              24
#define LINUX_IPV6_RECVERR          25
#define LINUX_IPV6_V6ONLY           26

#endif // LINUX___UAPI_DEF_IPV6_OPTIONS

#endif // DARLING_EMULATION_CONVERSION_LINUX_LINUX_IN6_H
