#ifndef DARLING_EMULATION_CONVERSION_LINUX_LINUX_IOCTL_H
#define DARLING_EMULATION_CONVERSION_LINUX_LINUX_IOCTL_H

#include <emulation/conversion/variables/linux/asm/ioctl.h>

#endif // DARLING_EMULATION_CONVERSION_LINUX_LINUX_IOCTL_H
