#ifndef DARLING_EMULATION_CONVERSION_LINUX_LINUX_LIBC_COMPAT_H
#define DARLING_EMULATION_CONVERSION_LINUX_LINUX_LIBC_COMPAT_H

#ifndef LINUX___UAPI_DEF_IF_IFCONF
#define LINUX___UAPI_DEF_IF_IFCONF      1
#endif
#ifndef LINUX___UAPI_DEF_IF_IFMAP
#define LINUX___UAPI_DEF_IF_IFMAP       1
#endif
#ifndef LINUX___UAPI_DEF_IF_IFNAMSIZ
#define LINUX___UAPI_DEF_IF_IFNAMSIZ    1
#endif
#ifndef LINUX___UAPI_DEF_IF_IFREQ
#define LINUX___UAPI_DEF_IF_IFREQ       1
#endif
#ifndef LINUX___UAPI_DEF_IF_NET_DEVICE_FLAGS
#define LINUX___UAPI_DEF_IF_NET_DEVICE_FLAGS    1
#endif
#ifndef LINUX___UAPI_DEF_IF_NET_DEVICE_FLAGS_LOWER_UP_DORMANT_ECHO
#define LINUX___UAPI_DEF_IF_NET_DEVICE_FLAGS_LOWER_UP_DORMANT_ECHO  1
#endif

#ifndef LINUX___UAPI_DEF_IN_ADDR
#define LINUX___UAPI_DEF_IN_ADDR        1
#endif
#ifndef LINUX___UAPI_DEF_IN_IPPROTO
#define LINUX___UAPI_DEF_IN_IPPROTO     1
#endif
#ifndef LINUX___UAPI_DEF_IN_PKTINFO
#define LINUX___UAPI_DEF_IN_PKTINFO     1
#endif
#ifndef LINUX___UAPI_DEF_IP_MREQ
#define LINUX___UAPI_DEF_IP_MREQ        1
#endif
#ifndef LINUX___UAPI_DEF_SOCKADDR_IN
#define LINUX___UAPI_DEF_SOCKADDR_IN    1
#endif
#ifndef LINUX___UAPI_DEF_IN_CLASS
#define LINUX___UAPI_DEF_IN_CLASS       1
#endif

#ifndef LINUX___UAPI_DEF_IN6_ADDR
#define LINUX___UAPI_DEF_IN6_ADDR       1
#endif
#ifndef LINUX___UAPI_DEF_IN6_ADDR_ALT
#define LINUX___UAPI_DEF_IN6_ADDR_ALT   1
#endif
#ifndef LINUX___UAPI_DEF_SOCKADDR_IN6
#define LINUX___UAPI_DEF_SOCKADDR_IN6   1
#endif
#ifndef LINUX___UAPI_DEF_IPV6_MREQ
#define LINUX___UAPI_DEF_IPV6_MREQ      1
#endif
#ifndef LINUX___UAPI_DEF_IPPROTO_V6
#define LINUX___UAPI_DEF_IPPROTO_V6     1
#endif
#ifndef LINUX___UAPI_DEF_IPV6_OPTIONS
#define LINUX___UAPI_DEF_IPV6_OPTIONS   1
#endif
#ifndef LINUX___UAPI_DEF_IN6_PKTINFO
#define LINUX___UAPI_DEF_IN6_PKTINFO    1
#endif
#ifndef LINUX___UAPI_DEF_IP6_MTUINFO
#define LINUX___UAPI_DEF_IP6_MTUINFO    1
#endif

#ifndef LINUX___UAPI_DEF_XATTR
#define LINUX___UAPI_DEF_XATTR          1
#endif

#endif // DARLING_EMULATION_CONVERSION_LINUX_LINUX_IOCTL_H
