#ifndef DARLING_EMULATION_CONVERSION_LINUX_LINUX_MMAN_H
#define DARLING_EMULATION_CONVERSION_LINUX_LINUX_MMAN_H

#include <emulation/conversion/variables/linux/asm-generic/hugetlb_encode.h>

#define LINUX_MAP_SHARED  0x01
#define LINUX_MAP_PRIVATE 0x02

#define LINUX_MAP_HUGE_SHIFT LINUX_HUGETLB_FLAG_ENCODE_SHIFT
#define LINUX_MAP_HUGE_MASK  LINUX_HUGETLB_FLAG_ENCODE_MASK

#endif // DARLING_EMULATION_CONVERSION_LINUX_LINUX_MMAN_H