#ifndef DARLING_EMULATION_CONVERSION_LINUX_LINUX_TCP_H
#define DARLING_EMULATION_CONVERSION_LINUX_LINUX_TCP_H

#define LINUX_TCP_NODELAY     1
#define LINUX_TCP_MAXSEG      2
#define LINUX_TCP_CORK        3
#define LINUX_TCP_KEEPIDLE    4
#define LINUX_TCP_KEEPINTVL   5
#define LINUX_TCP_KEEPCNT     6

#endif // DARLING_EMULATION_CONVERSION_LINUX_LINUX_TCP_H